
ERROR 2020-11-16 17:59:59 "Animeeeee!", articles.views views.py line 76, in anime_articles_list
WARNING [2020-11-16 18:19:49] "Not Found: /articles/anime_articles/hjkl", django.request log.py line 222, in log_response
WARNING [2020-11-16 18:23:40] "Not Found: /articles/124/delete_comment/", django.request log.py line 222, in log_response
WARNING [2020-11-16 18:23:49] "Not Found: /articles/150/delete_comment/", django.request log.py line 222, in log_response
WARNING [2020-11-16 18:25:00] "Not Found: /articles/273/delete", django.request log.py line 222, in log_response
WARNING [2020-11-16 18:25:04] "Not Found: /articles/273/delete/", django.request log.py line 222, in log_response
ERROR [2020-11-16 18:25:18] "Internal Server Error: /articles/273/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\konfetka\my_env\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
TypeError: get() missing 1 required positional argument: 'header'
WARNING [2020-11-16 18:25:54] "Not Found: /articles/273/edit_comment/", django.request log.py line 222, in log_response
ERROR [2020-11-16 18:27:18] "Internal Server Error: /articles/273/update_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\konfetka\my_env\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
TypeError: get() missing 1 required positional argument: 'header'
ERROR [2020-11-16 18:33:55] "Internal Server Error: /articles/273/update_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\konfetka\my_env\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
TypeError: get() missing 1 required positional argument: 'header'
ERROR [2020-11-16 18:33:57] "Internal Server Error: /articles/273/update_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\konfetka\my_env\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
TypeError: get() missing 1 required positional argument: 'header'
WARNING [2020-11-17 11:05:46] "Not Found: /favicon.ico", django.request log.py line 222, in log_response
ERROR [2020-11-17 11:06:18] "Internal Server Error: /articles/273/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\konfetka\my_env\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
TypeError: get() missing 1 required positional argument: 'header'
ERROR [2020-11-17 11:10:55] "Internal Server Error: /articles/273/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\konfetka\my_env\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
TypeError: get() missing 1 required positional argument: 'header'
ERROR [2020-11-17 11:10:57] "Internal Server Error: /articles/273/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\konfetka\my_env\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
TypeError: get() missing 1 required positional argument: 'header'
ERROR [2020-11-17 11:13:44] "Internal Server Error: /articles/retsenziia-na-anime-psikhopasport/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "D:\konfetka\my_env\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "D:\konfetka\my_env\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\konfetka\articles\views.py", line 91, in article_detail
    total_views = r.incr(f'article:{article.id}:views')
  File "D:\konfetka\my_env\lib\site-packages\redis\client.py", line 1641, in incr
    return self.incrby(name, amount)
  File "D:\konfetka\my_env\lib\site-packages\redis\client.py", line 1650, in incrby
    return self.execute_command('INCRBY', name, amount)
  File "D:\konfetka\my_env\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\konfetka\my_env\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "D:\konfetka\my_env\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
ERROR [2020-11-17 11:22:42] "Internal Server Error: /articles/273/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\konfetka\my_env\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
TypeError: get() missing 1 required positional argument: 'header'
ERROR [2020-11-17 11:23:50] "Internal Server Error: /articles/273/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\konfetka\my_env\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
TypeError: get() missing 1 required positional argument: 'header'
ERROR [2020-11-17 11:24:01] "Internal Server Error: /articles/273/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\konfetka\my_env\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
TypeError: get() missing 1 required positional argument: 'header'
WARNING [2020-11-17 11:35:40] "Forbidden (Permission denied): /articles/273/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\konfetka\common\decorators.py", line 23, in _wrapped_view
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
WARNING [2020-11-17 11:35:41] "Forbidden (Permission denied): /articles/273/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\konfetka\common\decorators.py", line 23, in _wrapped_view
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
ERROR [2020-11-17 12:41:24] "Internal Server Error: /articles/273/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\konfetka\common\decorators.py", line 23, in _wrapped_view
    raise HttpResponseBadRequest()
TypeError: exceptions must derive from BaseException
ERROR [2020-11-17 12:41:26] "Internal Server Error: /articles/273/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\konfetka\common\decorators.py", line 23, in _wrapped_view
    raise HttpResponseBadRequest()
TypeError: exceptions must derive from BaseException
WARNING [2020-11-17 12:43:34] "Forbidden (Permission denied): /articles/273/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\konfetka\common\decorators.py", line 21, in _wrapped_view
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
WARNING [2020-11-17 13:31:56] "Not Found: /favicon.ico", django.request log.py line 222, in log_response
WARNING [2020-11-17 13:37:48] "Forbidden (Permission denied): /articles/276/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\konfetka\common\decorators.py", line 17, in _wrapped_view
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
ERROR [2020-11-17 13:47:51] "Internal Server Error: /articles/276/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: _wrapped_view() missing 1 required positional argument: 'comment'
ERROR [2020-11-17 13:51:47] "Internal Server Error: /articles/276/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: _wrapped_view() missing 1 required positional argument: 'comment'
ERROR [2020-11-17 13:52:07] "Internal Server Error: /articles/276/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: _wrapped_view() missing 1 required positional argument: 'comment'
ERROR [2020-11-17 14:04:55] "Internal Server Error: /articles/276/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: _wrapped_view() got an unexpected keyword argument 'comment_id'
ERROR [2020-11-17 14:08:36] "Internal Server Error: /articles/272/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view articles.views.delete_comment didn't return an HttpResponse object. It returned None instead.
WARNING [2020-11-17 14:09:58] "Forbidden (Permission denied): /articles/272/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\konfetka\common\decorators.py", line 35, in _wrapped_view
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
WARNING [2020-11-17 14:10:15] "Forbidden (Permission denied): /articles/272/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\konfetka\common\decorators.py", line 35, in _wrapped_view
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
WARNING [2020-11-17 14:27:13] "Forbidden (Permission denied): /articles/276/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\konfetka\common\decorators.py", line 18, in _wrapped_view
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
WARNING [2020-11-17 14:35:14] "Forbidden (Permission denied): /articles/272/delete_comment/", django.request log.py line 222, in log_response
Traceback (most recent call last):
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\konfetka\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\konfetka\common\decorators.py", line 18, in _wrapped_view
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
